### ISSUE TITLE
<class 'selenium.common.exceptions.TimeoutException'> occured! Retrying..

### ISSUE THREAD

**Issue by fluffyloopy** [ed-archer/animepahe-dlr#23]
![image](https://user-images.githubusercontent.com/36381994/131477726-fb82ded5-ef84-4a6a-8387-460dd7214a92.png)
![image](https://user-images.githubusercontent.com/36381994/131479323-55ef010a-3449-417a-a2db-d96a3ff17cfd.png)

**Comment by ajxv** [comment]
Looks like cloudflare is detecting firefox webdriver as a bot. 
Will let you know when a solution is found.

**Comment by ajxv** [comment]
@fluffyloopy it seems all animepahe domains have adopted cloudflare's ddos guard. So the script may not work anymore. I am currently looking for a workaround. Will update if i find a solution.
